version: '3'

services:

  app:
    build: .
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine3.18
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: encoder